# Generated by Django 3.2.6 on 2021-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
